### ISSUE TITLE
CMP (IAB Reg.)

### ISSUE THREAD

**Issue by cwbeck** [appnexus/cmp#110]
It would seem this CMP is still not registered with the IAB. Are there any plans to register it?

http://advertisingconsent.eu/cmp-list/

**Comment by nhagen** [comment]
> AppNexus is not planning on registering as a CMP so we will not have our own subdomain. Going forward if you want consent stored on the consensu.org domain you would need to point to a "portal" on one of those subdomains.

https://github.com/appnexus/cmp/issues/37#issuecomment-389600413

This is the IAB reference implementation for the JS spec. If you intend to use this library as your CMP with access to global vendor consents, you will need to register as your own CMP and configure this library to use your CMP ID. If you don't use a registered CMP ID, its likely that vendors using your consent string will consider it invalid because there is no valid CMP with the ID === 1.

**Comment by krishoyt** [comment]
AppNexus still has no plans to register this CMP.
